# Generated by Django 4.2.7 on 2023-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100)),
                ('inscrit', models.CharField(max_length=70)),
                ('S1', models.CharField(max_length=100)),
                ('S2', models.CharField(max_length=100)),
            ],
        ),
    ]
